config/routes.rb
Rails.application.routes.draw do
  root to: 'tasks#index'

  resources :passwords, controller: "clearance/passwords", only: [:create, :new]
  resource :session, controller: "clearance/sessions", only: [:create]

  resources :users, controller: "clearance/users", only: [:create, :show] do
    resource :password,
      controller: "clearance/passwords",
      only: [:create, :edit, :update]
  end

  resources :projects do
    resources :tasks
  end

  get "/sign-in" => "clearance/sessions#new", as: "sign_in"
  delete "/sign-out" => "clearance/sessions#destroy", as: "sign_out"
  get "/sign-up" => "clearance/users#new", as: "sign_up"
  get '/tasks' => 'tasks#index', as: 'all_tasks'
  get '/tasks/today' => 'tasks#due_today', as: 'tasks_today'
  get '/tasks/upcoming' => 'tasks#upcoming', as: 'tasks_upcoming'
  get '/tasks/overdue' => 'tasks#overdue', as: 'tasks_overdue'
  put '/projects/:project_id/tasks/:id/complete' => 'tasks#mark_complete', as: 'mark_task_complete'
  put '/projects/:project_id/tasks/:id/incomplete' => 'tasks#mark_incomplete', as: 'mark_task_incomplete'
  get '/projects/:project_id/tasks/completed' => 'tasks#completed', as: 'completed_tasks'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/project.rb
class Project < ApplicationRecord
  belongs_to :user
  has_many :tasks, dependent: :destroy

  validates :description, length: { maximum: 500 }
  validates :name, presence: :true, uniqueness: { scope: :user_id, case_sensitive: false }, length: { in: 2..64 }

  def to_param
    [id, name.parameterize].join('-')
  end
end

app/models/task.rb
class Task < ApplicationRecord
  belongs_to :project

  validates :description, length: { maximum: 500 }
  validates :due_date, presence: :true
  validates :name, presence: :true, length: { maximum: 256 }

  scope :complete, -> { where(status: 'complete') }
  scope :incomplete, -> { where(status: 'incomplete') }
  scope :due_today, -> { where(due_date: Time.zone.now.all_day) }
  scope :upcoming, -> { where(due_date: Time.zone.now.all_week(:sunday)) }
  scope :overdue, -> { where(due_date: (Time.zone.now.at_beginning_of_year)..(Time.zone.now.yesterday.beginning_of_day)) }
end

app/models/user.rb
class User < ApplicationRecord
  include Clearance::User

  has_many :projects, -> { order(name: :asc) }, dependent: :destroy
  has_many :tasks, through: :projects

  # TODO: is this required by Clearance gem?
  attr_accessor :username
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include Clearance::Controller
  protect_from_forgery
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  before_action :require_login

  def index
    if params[:search]
      @projects = current_user.projects.where('lower(name) LIKE ?', "%#{params[:search].downcase}%")
    else
      @projects = current_user.projects
    end
  end

  def show
    @project = current_user.projects.find(params[:id])
    @tasks = @project.tasks.incomplete
  end

  def new
    @project = current_user.projects.build
  end

  def create
    @project = current_user.projects.build(project_params)
    if @project.save
      redirect_to @project, :notice => "The project has been created."
    else
      flash.now[:alert] = "Fix the errors below and try again."
      render :new
    end
  end

  def edit
    @project = current_user.projects.find(params[:id])
  end

  def update
    @project = current_user.projects.find(params[:id])
    if @project.update(project_params)
      redirect_to @project, :notice => "The project details have been updated."
    else
      flash.now[:alert] = "Fix the errors below and try again."
      render :edit
    end
  end

  def destroy
    @project = current_user.projects.find(params[:id])
    @project.destroy
    redirect_to root_path, :notice => "The project has been removed."
  end

  private

  def project_params
    params.require(:project).permit(:description, :name)
  end
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_action :require_login

  def index
    @projects = current_user.projects.order(name: :asc).includes(:tasks).where('tasks.status' => 'incomplete')
  end

  def show
    @project = current_user.projects.find(params[:project_id])
    @task = @project.tasks.find(params[:id])
  end

  def new
    @project = current_user.projects.find(params[:project_id])
    @task = @project.tasks.build
  end

  def create
    @project = current_user.projects.find(params[:project_id])
    @task = @project.tasks.build(task_params)
    if @task.save
      Project.increment_counter(:incomplete_tasks, params[:project_id])
      redirect_to @project, :notice => "The task has been added to the project."
    else
      flash.now[:alert] = "Fix the errors below and try again."
      render :new
    end
  end

  def edit
    @project = current_user.projects.find(params[:project_id])
    @task = @project.tasks.find(params[:id])
  end

  def update
    @project = current_user.projects.find(params[:project_id])
    @task = @project.tasks.find(params[:id])
    if @task.update(task_params)
      redirect_to [@project, @task], :notice => "The task details have been updated."
    else
      flash.now[:alert] = "Fix the errors below and try again."
      render :edit
    end
  end

  def destroy
    @project = current_user.projects.find(params[:project_id])
    @task = @project.tasks.find(params[:id])
    @task.destroy
    if @task.status == 'complete'
      Project.decrement_counter(:complete_tasks, params[:project_id])
    else
      Project.decrement_counter(:incomplete_tasks, params[:project_id])
    end
    redirect_to @project, :notice => "The task has been removed from the project."
  end

  def mark_complete
    @task = current_user.tasks.find(params[:id])
    @task.update_column(:status, 'complete')
    Project.increment_counter(:complete_tasks, params[:project_id])
    Project.decrement_counter(:incomplete_tasks, params[:project_id])
    redirect_to project_path(params[:project_id]), :notice => "The task has been marked as complete."
  end

  def mark_incomplete
    @task = current_user.tasks.find(params[:id])
    @task.update_column(:status, 'incomplete')
    Project.increment_counter(:incomplete_tasks, params[:project_id])
    Project.decrement_counter(:complete_tasks, params[:project_id])
    redirect_to project_path(params[:project_id]), :notice => "The task has been marked as incomplete."
  end

  def completed
    @project = current_user.projects.includes(:tasks).where('tasks.status' => 'complete').find(params[:project_id])
  end

  %w(due_today upcoming overdue).each do |due_window|
    define_method "#{due_window}" do
      @projects = []
      current_user.projects.each do |project|
        @projects.push(project) if project.tasks.incomplete.send(due_window).any?
      end
      @tasks = current_user.tasks.incomplete.send(due_window)
      @due_window = due_window
      render :due_window
    end
  end

  private

  def task_params
    params.require(:task).permit(:description, :due_date, :estimate, :name)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def avatar_url(user)
    gravatar_id = Digest::MD5::hexdigest(user.email).downcase
    "http://gravatar.com/avatar/#{gravatar_id}.jpg?s=48&d=mm"
  end
end

app/helpers/password_resets_helper.rb
module PasswordResetsHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="utf-8" />
	<meta http-equiv="X-UA-Compatible" content="IE=edge" />
	<meta name="viewport" content="width=device-width, initial-scale=1" />

	<title>Due It</title>
	<meta name="description" content="Simple project management for individuals or small teams." />
	<meta name="author" content="Matt Halliday, matthalliday.ca" />

	<%= stylesheet_link_tag "application" %>
	<script src="https://use.typekit.net/wld4wpn.js"></script>
	<script>try{Typekit.load({ async: true });}catch(e){}</script>
	<%= javascript_include_tag "application" %>
	<%= csrf_meta_tags %>
</head>
<body>
	<a href="#content" class="visuallyhidden focusable skipper">Skip to content</a>

	<header class="app-banner" role="banner">
		<div class="inner clearfix">
			<h1 class="branding"><%= link_to 'Due It', root_path %></h1>

			<nav class="app-navigation" role="navigation">
				<%= render 'shared/navigation' %>
			</nav>
		</div>
	</header><!-- /.app-banner -->

	<main id="content" class="app-content" role="main" tabindex="-1">
		<% flash.each do |key, value| %>
			<%= content_tag(:div, content_tag(:p, value), class: "flash #{key}") %>
		<% end %>

		<%= yield %>
	</main><!-- /.app-content -->

	<footer class="app-footer" role="contentinfo">
		<p>Built with <a href="http://rubyonrails.org" title="Version <%= Rails.version %>">Ruby on Rails</a></p>
	</footer><!-- /.app-footer -->
</body>
</html>

app/views/projects/_form.html.erb
<%= form_for @project do |f| %>
	<%= render 'shared/errors', object: @project %>

	<div class="field model-name">
		<%= f.label :name, 'Name *' %>
		<%= f.text_field :name %>
	</div>
	<div class="field">
		<%= f.label :description %>
		<%= f.text_area :description, rows: 8 %>
	</div>
	<div class="field submit">
		<%= f.submit %>
	</div>
<% end %>

app/views/projects/edit.html.erb
<article>
	<h1 class="page-title">Edit Project</h1>

	<div class="project">
		<div class="project-name">
			<h1><%= link_to @project.name, @project %></h1>
		</div>

		<div class="info-bar clearfix">
			<p class="message">Fields with an asterisk are required</p>
			<%= link_to 'Remove Project', @project, method: :delete, confirm: 'Delete this project and its tasks?', class: 'button' %>
		</div>

		<%= render 'form' %>
	</div><!-- /.project -->
</article>

app/views/projects/index.html.erb
<section>
	<% if params[:search] %>
		<h1 class="page-title">Search Projects</h1>
	<% else %>
		<h1 class="page-title">All Projects</h1>
	<% end %>

	<% if params[:search] && @projects.empty? %>
		<%= content_tag(:p, "Couldn't find any projects with the name <strong>#{params[:search]}</strong>".html_safe, class: 'page-message') %>
	<% elsif @projects.empty? %>
		<%= content_tag(:p, "You don't have any projects &ndash; why not #{link_to 'add one', new_project_path}?".html_safe, class: 'page-message') %>
	<% end %>

	<% @projects.each do |project| %>
		<article class="project">
			<div class="project-name">
				<h1><%= link_to project.name, project %></h1>
			</div>

			<div class="info-bar clearfix">
				<p class="task-count"><%= pluralize(project.incomplete_tasks, 'incomplete task', 'incomplete tasks') %></p>
				<%= link_to 'Add Task', new_project_task_path(project), class: 'button' %>
			</div>

			<div class="desc"><%= simple_format project.description %></div>
		</article><!-- /.project -->
	<% end %>
</section>

app/views/projects/new.html.erb
<article class="project">
	<div class="project-name">
		<h1>Add Project</h1>
	</div>

	<div class="info-bar clearfix">
		<p class="message">Fields with an asterisk are required</p>
	</div>

	<%= render 'form' %>
</article><!-- /.project -->

app/views/projects/show.html.erb
<article class="project">
	<div class="project-name">
		<h1><%= @project.name %></h1>
	</div>

	<div class="info-bar clearfix">
		<p class="task-count"><%= pluralize(@project.incomplete_tasks, 'incomplete task', 'incomplete tasks') %></p>
		<%= link_to 'Add Task', new_project_task_path(@project), class: 'button' %>
	</div>

	<ul class="task-list">
		<%= render partial: @tasks, locals: { project: @project } %>
	</ul><!-- /.task-list -->
</article><!-- /.project -->

<%= link_to 'Completed Tasks', completed_tasks_path(@project) if @project.complete_tasks > 0 %>
<%= link_to 'Edit Project', edit_project_path(@project) %>

app/views/shared/_errors.html.erb
<% if object.errors.any? %>
	<div class="errors">
		<h2>Please fix the following <%= pluralize(object.errors.count, 'error') %>:</h2>
		<ul>
			<% object.errors.full_messages.each do |msg| %>
				<%= content_tag(:li, msg) %>
			<% end %>
		</ul>
	</div>
<% end %>

app/views/shared/_navigation.html.erb
<ul class="nav-collection clearfix">
	<% if signed_in? %>
		<li class="nav-item">
			<span class="nav-title">Tasks</span>
			<ul class="sub-nav-collection clearfix">
				<li class="sub-nav-item"><%= link_to 'All', all_tasks_path %></li>
				<li class="sub-nav-item"><%= link_to 'Today', tasks_today_path %></li>
				<li class="sub-nav-item"><%= link_to 'Upcoming', tasks_upcoming_path %></li>
				<li class="sub-nav-item"><%= link_to 'Overdue', tasks_overdue_path %></li>
			</ul>
		</li>
		<li class="nav-item">
			<span class="nav-title">Projects</span>
			<ul class="sub-nav-collection clearfix">
				<li class="sub-nav-item"><%= link_to 'All', projects_path %></li>
				<li class="sub-nav-item"><%= link_to 'Add New', new_project_path %></li>
			</ul>
		</li>
		<li class="nav-item">
			<span class="nav-title">Account</span>
			<ul class="sub-nav-collection clearfix">
				<li class="sub-nav-item"><%= current_user.email %></li>
				<li class="sub-nav-item"><%= link_to 'Sign Out', sign_out_path, method: :delete %></li>
			</ul>
		</li>
		<li class="nav-item">
			<span class="nav-title">Search</span>
			<%= form_tag projects_path, method: 'get', class: 'search-form', role: 'search' do %>
				<%= label_tag :search, nil, class: 'visuallyhidden' %>
				<%= search_field_tag :search, params[:search] %>
				<%= submit_tag "Search", name: nil, class: 'visuallyhidden' %>
			<% end %>
		</li>
	<% else %>
		<li class="nav-item">
			<span class="nav-title">Account</span>
			<ul class="sub-nav-collection clearfix">
				<li class="sub-nav-item"><%= link_to 'Sign In', sign_in_path %></a></li>
				<li class="sub-nav-item"><%= link_to 'Sign Up', sign_up_path %></li>
			</ul>
		</li>
	<% end %>
</ul><!-- /.nav-collection -->

app/views/tasks/_form.html.erb
<%= form_for [@project, @task] do |f| %>
	<%= render 'shared/errors', object: @task %>

	<div class="field model-name">
		<%= f.label :name, 'Name *' %>
		<%= f.text_field :name %>
	</div>
	<div class="field">
		<%= f.label :description %>
		<%= f.text_area :description, rows: 8 %>
	</div>
	<div class="field-wrap">
		<div class="field estimate">
			<%= f.label :estimate %>
			<%= f.text_field :estimate %>
		</div>
		<div class="field due-date">
			<%= f.label :due_date, 'Due Date *' %>
			<%= f.date_select :due_date,
			                  default: Time.zone.now.end_of_week(:saturday),
			                  order: [:month, :day] %>
		</div>
	</div>
	<div class="field submit">
		<%= f.submit %>
	</div>
<% end %>

app/views/tasks/_task.html.erb
<li>
	<h2><%= link_to task.name, [project, task] %></h2>
	<div class="meta clearfix">
		<p>Estimated <%= task.estimate %></p>
		<p>Due on <%= task.due_date.strftime('%B %-d') %></p>

		<% # TODO make this less terrible %>
		<% if task.status == 'incomplete' %>
			<%= link_to 'Complete', mark_task_complete_path(project, task), method: :put, class: 'task-action complete' %>
		<% elsif task.status == 'complete' %>
			<%= link_to 'Mark as Incomplete', mark_task_incomplete_path(project, task), method: :put, class: 'task-action complete' %>
		<% end %>
	</div>
</li>

app/views/tasks/completed.html.erb
<article class="project">
	<div class="project-name">
		<h1><%= link_to @project.name, @project %></h1>
	</div>

	<div class="info-bar clearfix">
		<p class="task-count"><%= pluralize(@project.complete_tasks, 'completed task', 'completed tasks') %></p>
	</div>

	<ul class="task-list">
		<%= render partial: @project.tasks, locals: { project: @project } %>
	</ul><!-- /.task-list -->
</article><!-- /.project -->

app/views/tasks/due_window.html.erb
<section>
	<h1 class="page-title"><%= @due_window.titleize %></h1>
	<% if @tasks.empty? %>
		<%= content_tag(:p, "Looks like there's nothing #{@due_window.humanize.downcase}!", class: 'page-message') %>
	<% end %>

	<% @projects.each do |project| %>
		<article class="project">
			<div class="project-name">
				<h1><%= link_to project.name, project %></h1>
			</div>

			<div class="info-bar clearfix">
				<p class="task-count"><%= pluralize(project.incomplete_tasks, 'incomplete task', 'incomplete tasks') %></p>
				<%= link_to 'Add Task', new_project_task_path(project), class: 'button' %>
			</div>

			<ul class="task-list">
				<%= render partial: project.tasks.incomplete.send(@due_window), locals: { project: project } %>
			</ul><!-- /.task-list -->
		</article><!-- /.project -->
	<% end %>
</section>

app/views/tasks/edit.html.erb
<article>
	<h1 class="page-title">Edit Task</h1>

	<div class="project">
		<div class="project-name">
			<h1><%= link_to @project.name, @project %></h1>
		</div>

		<div class="info-bar clearfix">
			<p class="message">Fields with an asterisk are required</p>
			<%= link_to 'Remove Task', [@project, @task], method: :delete, confirm: 'Delete this task?', class: 'button' %>
		</div>

		<%= render 'form' %>
	</div><!-- /.project -->
</article>

app/views/tasks/index.html.erb
<section>
	<h1 class="page-title">All Tasks</h1>
	<% if @projects.empty? %>
		<%= content_tag(:p, "You currently don't have any tasks", class: 'page-message') %>
	<% end %>

	<% @projects.each do |project| %>
		<article class="project">
			<div class="project-name">
				<h1><%= link_to project.name, project %></h1>
			</div>

			<div class="info-bar clearfix">
				<p class="task-count"><%= pluralize(project.incomplete_tasks, 'incomplete task', plural: 'incomplete tasks') %></p>
				<%= link_to 'Add Task', new_project_task_path(project), class: 'button' %>
			</div>

			<ul class="task-list">
				<%= render partial: project.tasks, locals: { project: project } %>
			</ul><!-- /.task-list -->
		</article><!-- /.project -->
	<% end %>
</section>

app/views/tasks/new.html.erb
<article>
	<h1 class="page-title">Add Task</h1>

	<div class="project">
		<div class="project-name">
			<h1><%= link_to @project.name, @project %></h1>
		</div>

		<div class="info-bar clearfix">
			<p class="message">Fields with an asterisk are required</p>
		</div>

		<%= render 'form' %>
	</div><!-- /.project -->
</article>

app/views/tasks/show.html.erb
<article class="project">
	<div class="project-name">
		<h1><%= link_to @project.name, @project %></h1>
	</div>

	<div class="info-bar clearfix">
		<p class="task-count"><%= pluralize(@project.incomplete_tasks, 'incomplete task', 'incomplete tasks') %></p>
		<%= link_to 'Add Task', new_project_task_path(@project), class: 'button' %>
	</div>

	<ul class="task-list">
		<li>
			<h2><%= @task.name %></h2>
			<% unless @task.description.blank? %>
				<div class="desc"><%= simple_format @task.description %></div>
			<% end %>

			<div class="meta clearfix">
				<p>Estimated <%= @task.estimate %></p>
				<p>Due on <%= @task.due_date.strftime('%B %-d') %></p>

				<% if @task.status == 'incomplete' %>
					<%= link_to 'Complete', mark_task_complete_path(@project, @task), method: :put, class: 'task-action complete' %>
				<% end %>
			</div>
		</li>
	</ul><!-- /.task-list -->
</article><!-- /.project -->

<%= link_to 'Edit Task', edit_project_task_path(@project, @task) %>

app/views/tasks/this_week.html.erb
<% # TODO refactor views for all due date based views %>
<article>
	<h1>Due this week</h1>
	<%= raw "Looks like there's nothing due this week" if @tasks.empty? %>

	<ul>
		<% @tasks.each do |task| %>
			<li>
				<h2><%= link_to task.name, Project.find(task.project_id) %></h2>
				<p>Due: <strong><%= task.due_date.strftime('%B %-d') %></strong></p>
			</li>
		<% end %>
	</ul>
</article>

app/views/users/_form.html.erb
<div class="field">
  <%= form.label :email, 'Email *' %>
  <%= form.text_field :email, type: 'email' %>
</div>

<div class="field">
  <%= form.label :password, 'Password *' %>
  <%= form.password_field :password %>
</div>

app/views/users/new.html.erb
<div class="project">
	<div class="project-name">
		<h1><%= t(".title") %></h1>
	</div>

	<div class="info-bar clearfix">
		<p class="message">Fields with an asterisk are required</p>
	</div>

  <%= form_for @user do |form| %>
    <%= render partial: '/users/form', object: form %>

    <div class="submit-field">
      <%= form.submit 'Sign Up' %>
    </div>
  <% end %>
</div><!-- /.project -->